<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Exporting_a_selection_from_Excel</RootNamespace>
    <AssemblyName>ExcelExport.Core</AssemblyName>
    <OutputType>Library</OutputType>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="EPPlus" Version="6.1.2" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="2.2.1" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.3" />
  </ItemGroup>
</Project>
